%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/calypso/Dropbox/397/everything.csv
%
% Auto-generated by MATLAB on 18-Aug-2020 14:51:28

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 28);

% Specify range and delimiter
opts.DataLines = [100, Inf];
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["time", "Milliseconds", "levelCounter", "correctCounter", "leftHandPosition", "leftHandRotation", "rightHandPosition", "rightHandRotation", "redBallPosition", "redBallRotation", "leftHandGrab", "rightHandGrab", "feedbackType", "leftHandVibration", "rightHandVibration", "correctBallPosition", "lastTemplateBallPosition", "areCalibratingGhostHandsActive", "areGrabbingGhostHandsActive", "calibrationState", "isCalibrationBlocked", "grabbingState", "buttonHasBeenPressed", "buttonCurrentlyPressed", "headPosition", "headRotation", "isExplosionTriggered", "ECG"];
opts.VariableTypes = ["datetime", "double", "double", "double", "string", "string", "string", "string", "string", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["leftHandPosition", "leftHandRotation", "rightHandPosition", "rightHandRotation", "redBallPosition", "redBallRotation", "leftHandGrab", "rightHandGrab", "feedbackType", "leftHandVibration", "rightHandVibration", "correctBallPosition", "lastTemplateBallPosition", "areCalibratingGhostHandsActive", "areGrabbingGhostHandsActive", "calibrationState", "isCalibrationBlocked", "grabbingState", "buttonHasBeenPressed", "buttonCurrentlyPressed", "headPosition", "headRotation", "isExplosionTriggered"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "time", "InputFormat", "yyyy-MM-dd HH:mm:ss.SSS");
opts = setvaropts(opts, "ECG", "TrimNonNumeric", true);
opts = setvaropts(opts, "ECG", 'DecimalSeparator', ",");

% Import the data
% This preallocates space
all= [];
% This gets kist of folders and files. 
mainFolder = join([allFolder ptcp],'');
subdirs = dir(mainFolder);
%This filters out all the items in the main folder that are not directories
subdirs(~[subdirs.isdir]) = [];
%And this filters out the parent and current directory '.' and '..'
tf = ismember( {subdirs.name}, {'.','..'});
subdirs(tf) = [];
numberOfFolders = length(subdirs);

for j=1:numberOfFolders % this is to go through every folder 
    thissubdir = subdirs(j).name;
    subdirpath = join([mainFolder '/' thissubdir],'');
    data = readtable(subdirpath + "/everything.csv", opts);
    data.set = ones(height(data),1)*j; 
% %     if data.set ==1
% %         data.ECG = (data.ECG*-1)+700;
% %         %data.ECG = (data.ECG-min(data.ECG))/(max(data.ECG)-min(data.ECG));
% %     else
%     %data.ECG = (data.ECG-min(data.ECG))/(max(data.ECG)-min(data.ECG));
%     end
    all = [all ; data];
end
%% Clear temporary variables
clear opts data j subdirpath tf thissubdir subdirs mainFolder
all = rmmissing(all);
%data.ECG = str2double(strrep(data.ECG,',','.'));





